project:
  type: website
  output-dir: docs
  execute-dir: project


website:
  title: 'Lab Resources & Policies'
  page-navigation: true
  reader-mode: false
  repo-url: https://github.com/wwalk-lab/internal-resources
  repo-actions: [edit]
  sidebar:
    style: "docked"
    logo: "imgs/WWALK_logo.png"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Lab Policies"
        href: policies/00-policies.qmd
        contents:
          - href: policies/01-code-of-conduct.qmd
            text: Lab Code of Conduct
          - href: policies/02-data-management.qmd
            text: WWALK Data Management
          - href: policies/03-lab-computer.qmd
            text: George (Lab Computer)
      - section: "Lab Resources"
        href: resources/00-lab-resources.qmd
        contents:
          - href: resources/01-shelby-images.qmd
            text: Shelby's Drawings
      - section: "Templates"
        href: templates/00-templates.qmd
        contents:
          - href: templates/01-data-sharing.qmd
            text: Data Sharing Agreement Template
          - href: templates/02-ethics.qmd
            text: University of Calgary Ethics Application
      - section: "Other Resources"
        href: other-resources/00-other-resources.qmd
        contents:
          - href: other-resources/01-wwalk-lab-reading-list.qmd
            text: WWALK Lab Reading List
          - href: other-resources/02-issa-resources.qmd
            text: iSSA Resources
format:
  html:
    theme: darkly
    toc: true
    css: styles.css
