# Lab Code of Conduct

*Adapted from [Christie Bahlai's](https://bahlailab.org/) code of conduct*

Science is already hard. The work of making sure science isn't harder than it needs to be is incumbent on all of us. We create our culture, and in the WWALK lab, our culture is rooted in humility, accountability, respect, equity, and anti-oppression.

Through our science and all that surrounds it, we strive to recognize and dismantle the systemic barriers placed upon marginalized people and to create a space where we/they can thrive.

\[jgh: idk how to phrase this properly but I think it's worth adding a line in here about how these policies don't just apply to our research, and that you can't draw a line between 'science' and the rest of the work we do?\]

Oppression and structures of power dynamics persist through being naturalized and invisible. To fight for equity, we all carry a responsibility to actively pay attention and call out the ways in which race, ethnicity, class, gender, sexual orientation, (dis)ability, and other factors affect our experiences and work against the oppressive systems causing these differences. Discrimination or harassment based on the above axes of marginalization, or any others, will not be tolerated. We do not tolerate harassment or discrimination by and/or of members of our community in any form.

In the WWALK Lab, we have the privilege of working with many Indigenous communities. This privilege comes with responsibilities of care, thoughtfulness, and humility. Scientific research has and continues to be a source of violence and pain for Indigenous communities. WWALK community members, specifically white community members, are expected to take the necessary steps to conduct ethical research and to educate themselves to avoid perpetuating harm through unintentionally racist interactions. If you are unsure how to start doing this, you can ask a senior graduate student.

\[jgh: add a sentence to the last paragraph linking to some resources? Does WWALK have like a don't-be-racist-101 list? TRC, etc.\]

Above we listed overtly exclusionary behaviours, however non-inclusive behavior can often include more subtle or indirect actions (i.e., microaggressions), and these actions can contribute to a hostile environment. Exclusionary behavior includes actions which may not target specific individuals but nevertheless contribute to an unwelcoming environment, and includes but is not limited to: preferential treatment of people based on markers of status or belonging in dominant social groups, dominating discussion or allowing specific individuals to dominate or talk-over discussion, and making statements or taking actions that contribute to the marginalization or ‘othering’ of groups of people. Exclusionary behavior can also manifest in scientific practice or policy development, and includes implicit or explicit endorsement of conservation or environmental actions that do harm to people living in those spaces, or exploitative extraction of data, labour or resources.

To make clear what is expected, we ask all members of the community to conform to the following Code of Conduct.

-   All professional communication - online and in person - should be appropriate for a professional audience including people of many different backgrounds. Sexual or discriminatory language and imagery is not appropriate at any time.
-   Be kind to others. Criticism is essential in science, but it must be constructive if we're going to move forward in a supportive, inclusive way. Also be kind to yourself - criticism of your work is not criticism of you as a person. Responsibility for not causing harm lies with the critic, but learning to take feedback with humility and honesty is important too.
-   Behave professionally. Harassment and sexist, racist, or exclusionary jokes are never appropriate, but even more generally, treat others with respect. Give colleagues your attention and courtesy.
-   Please make an effort to make an inclusive environment for everyone. Professionalism is not simply the absence of negative behaviours, but actively fostering positive interactions. Give everyone a chance to talk and an opportunity to contribute. Don't dominate, talk over, or try to compete with your colleagues. Lift up and make space.
-   Be aware that your actions can be hurtful to others or contribute to a negative environment even if you had no intent of harm. Impact =/= intent; we all make missteps. That's ok! Listen. Offer a genuine apology. Commit to learning and doing better.

*Unacceptable behaviour* includes offensive verbal and/or written comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of discussions, inappropriate physical contact, and unwelcome sexual attention.

Participants asked to stop any harassing or discriminatory behaviour are expected to comply immediately.

Members of the community who violate these rules - no matter how much they have contributed to the WWALK lab, or how specialized their skill set - will be approached by Ally. If inappropriate behaviour persists after a discussion with Ally, the issue will be escalated according to procedures laid out at the University of Calgary (see [Resources] below). The process may differ depending on the role of the individual (e.g., student, postdoc, employee).

As head of the WWALK Lab, Ally is the community leader in charge of handling issues regarding breaches in the code of conduct. You can report any issue to Ally and all communication will be treated as confidential. If the issue you have includes Ally, you can report it to X.

## Resources

-   University of Calgary: [Code of Conduct](https://www.ucalgary.ca/legal-services/sites/default/files/teams/1/Policies-Code-of-Conduct.pdf)

-   University of Calgary: [Complaints and Investigating Alleged Breaches](https://www.ucalgary.ca/hr/work-compensation/working-ucalgary/code-conduct/complaints-and-investigating-alleged-breaches)

-   University of Calgary: [Student Non-Academic Misconduct Procedure](https://www.ucalgary.ca/legal-services/sites/default/files/teams/1/Policies-Student-Non-Academic-Misconduct-Procedure.pdf)
